### ISSUE TITLE
I used this demo but i got blank data

### ISSUE THREAD

**Issue by mendaparadarshit** [Lightstreamer/Lightstreamer-example-StockList-client-ios#1]
I have download this demo and use for IG companion see screenshot below 

![simulator screen shot 29-apr-2016 2 06 03 pm](https://cloud.githubusercontent.com/assets/11643853/14911468/341d70f8-0e13-11e6-8404-d0f4a7952c52.png)

can you give me solution.. in this fileds what data i have to use??
# define PUSH_SERVER_URL            (@"https://adp.marketdatasystems.com:443")

//#define PUSH_SERVER_URL          (@"http://push.lightstreamer.com")
# define ADAPTER_SET                (@"DEMO")
# define DATA_ADAPTER               (@"QUOTE_ADAPTER")

**Comment by dario-weswit** [comment]
This is outside the scope of this example and can only be answered by IG itself. Try [this forum](https://labs.ig.com/community).
Note that each installation of Lightstreamer not only determines the Adapter Set and Data Adapter, but also the item names and field names, and usually a user name and password are required (to be supplied in the "connectionDetails" property before invoking "connect").
